name: t_store
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'






#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter

# utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.5
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

# Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
# State Management
  get: ^4.6.5
  get_storage: ^2.1.1

#--------------- ./ PACKAGE END -----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
  
#------------ LOCAL ASSETS ------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
# - assets/logos

#------------- local assets end -----------#

  
#------------ local fonts -----------------#
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - assets: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - assets: assets/fonts/Poppins-Italic.ttf
        weight: 500
        style: italic
      - assets: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - assets: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - assets: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - assets: assets/fonts/Poppins-Bold.ttf
        weight: 800
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
